[tool.poetry]
name = "blog"
version = "0.1.0"
description = ""
authors = ["Matt Florence <matt@mattflo.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
mkdocs-material = "^9.5.48"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
